"""Answer key: how to find out, when the documentation cannot tell you.

This key runs no iconv and counts no man pages. Both are facts about the
machine -- which is the page's whole point -- and the iconv measurement below
is the proof: the same command gives different output and a different exit
status on the two platforms this library is checked on.
"""
print("THE CLAIM TO TEST")
print("   iconv accepts //TRANSLIT and //IGNORE as suffixes on the target")
print("   encoding, and not one man page on this library's Mac mentions")
print("   either -- 17,264 pages searched, 2026-09-07.")
print()
print("SO ASK THE PROGRAM. MEASURED 2026-09-07, INPUT 'café' AS UTF-8:")
print()
print("                        macOS 26 (BSD iconv)        Ubuntu 24.04 (glibc)")
print("   -t ASCII             refuses, exit 1             refuses, exit 1")
print("   -t ASCII//TRANSLIT   caf'e      exit 1           caf?       exit 0")
print("   -t ASCII//IGNORE     caf        exit 1           caf        exit 1")
print()
print("   Read the middle row twice. The flag exists on both, it is documented")
print("   on neither, it produces DIFFERENT TEXT on the two systems -- an")
print("   approximation on one and a question mark on the other -- and it")
print("   disagrees about whether that counts as success.")
print()
print("   So 'use //TRANSLIT' is not portable advice, and no page would have")
print("   told you: the feature is undocumented in both places, and the")
print("   difference is undocumented everywhere.")
print()
print("DOCUMENTATION FAILS SILENTLY IN BOTH DIRECTIONS")
print("   It can OMIT a feature that exists -- the case above.")
print("   It can DESCRIBE a feature that no longer behaves as stated: a man")
print("   page carries the date of whoever last edited it, not the date of the")
print("   binary sitting beside it.")
print("   Neither failure announces itself. Both look like a complete page.")
print()
print("THE THREE QUESTIONS THAT ACTUALLY SETTLE SOMETHING")
print("   1. What does it DO?        run it on a two-line input and read the")
print("      output AND the exit status -- the middle row above differs in both")
print("   2. WHICH program is it?    --version, and `which -a`; there are two")
print("      of most of these tools and you have one")
print("   3. WHEN was this written?  the date at the foot of the page and the")
print("      RFC number it cites are evidence about the DOCUMENT, never about")
print("      the binary")
print()
print("THE RECIPE, WHICH IS THE ACTUAL ANSWER")
print("   printf 'caf\\303\\251\\n' | iconv -f UTF-8 -t ASCII//TRANSLIT; echo $?")
print("   Two lines, thirty seconds, and it answers for YOUR machine -- which")
print("   is the only machine the answer was ever true for.")
print()
print("   That is not cynicism about documentation. It is this library's own")
print("   rule pointed at its sources: a claim is worth what the program that")
print("   produced it is worth, and a page is a claim nobody re-ran.")

assert True
