"""Answer key: a page that is out of date and not wrong.

Nothing here reads your man pages: the point is what to DO with a date, and the
measurements are stated with the machine and the day they were taken.
"""
print("WHAT THE PAGE SAYS")
print("   man 5 utf8 on a 2026 Mac describes UTF-8 as encoding up to SIX bytes,")
print("   covering 0x00000000 to 0x7FFFFFFF, and cites RFC 2279.")
print()
print("WHAT IS TRUE OF UNICODE TODAY")
print("   RFC 3629 superseded RFC 2279 in NOVEMBER 2003. UTF-8 is at most FOUR")
print("   bytes and stops at U+10FFFF -- the ceiling UTF-16's surrogate pairs")
print("   can express. Five- and six-byte forms are ill-formed, and every")
print("   modern decoder rejects them.")
print(f"   the largest code point:   U+{0x10FFFF:X} = {0x10FFFF}")
print(f"   its UTF-8 length:         {len(chr(0x10FFFF).encode())} bytes")
print()
print("SO IS THE PAGE WRONG?")
print("   No -- and this is the part worth sitting with. That page documents")
print("   the machine's own iconv, which still ACCEPTS the six-byte forms it")
print("   describes. The page is an accurate description of a 1998 standard")
print("   that a 2026 binary still implements. Unicode moved; that copy of the")
print("   software did not; the page describes the software.")
print()
print("   'Out of date' and 'wrong' are different findings, and only one of")
print("   them tells you to stop reading.")
print()
print("THE THREE DATES ON ANY PAGE, AND WHAT EACH IS EVIDENCE OF")
print("   the date at the foot     when somebody last EDITED the page")
print("   the standard it cites    which version of the world it describes")
print("   the binary's --version   what will actually run")
print("   They are three independent facts and they are routinely years apart.")
print("   Only the third one is evidence about what your command will do.")
print()
print("HOW TO READ A PAGE THAT MIGHT BE OLD")
print("   1. Find the citation. An RFC number, an ISO number, a standard's")
print("      year -- that is the page telling you which era it is from.")
print("   2. Check whether that standard was superseded. RFC 2279 -> 3629 is")
print("      the example here; there are many.")
print("   3. Then ask the binary anyway, because a superseded standard that is")
print("      still implemented is exactly the situation that produces a bug")
print("      report nobody can reproduce.")
print()
print("AND THE REASON THIS MATTERS BEYOND MAN PAGES")
print("   The six-byte forms are not a curiosity. A decoder that accepts them")
print("   accepts a SECOND spelling for code points that already have one --")
print("   which is the overlong-sequence problem, and the reason RFC 3629")
print("   tightened the definition rather than merely narrowing the range.")

assert len(chr(0x10FFFF).encode()) == 4
assert 0x10FFFF == 1114111
