"""Answer key: four habits, and what each one prevents."""
import locale, os, sys

print("1. PASS encoding= TO EVERY open(), EVEN WHEN IT IS THE DEFAULT")
print(f"   locale.getpreferredencoding(False) is the default on your machine,")
print(f"   and it is NOT necessarily utf-8: it is cp1252 on a western Windows")
print(f"   box and the locale's charset elsewhere. This machine's answer is")
print(f"   deliberately not printed -- it would make this key a fact about the")
print(f"   runner, which is the whole problem the habit prevents.")
print("   forbidden:  open('data.csv')")
print("   correct:    open('data.csv', encoding='utf-8')")
print("   Same file, same code, different result on a colleague's laptop -- and")
print("   nothing in the traceback points at the open() call.")
print()
print("2. RUN THE TESTS ONCE UNDER -X warn_default_encoding")
print("   python3 -X warn_default_encoding -W error::EncodingWarning -m pytest")
print("   Every open() that relied on the default becomes a warning naming the")
print("   file and line. It is a one-off audit, not a permanent setting, and it")
print("   is the only way to find the ones you did not write.")
print()
print("3. FILENAMES ARE BYTES WEARING A COSTUME")
print(f"   sys.getfilesystemencoding()      {sys.getfilesystemencoding()!r}")
print(f"   sys.getfilesystemencodeerrors()  {sys.getfilesystemencodeerrors()!r}")
raw = b"caf\xe9.txt"
name = os.fsdecode(raw)
print(f"   os.fsdecode({raw!r}) -> {name!r}")
print(f"   os.fsencode(that)    -> {os.fsencode(name)!r}   round trip: {os.fsencode(name) == raw}")
print("   The name is not valid UTF-8 and Python still round-trips it, because")
print("   surrogateescape puts each undecodable byte in a lone surrogate. The")
print("   cost: that str cannot be encoded by anything else, so printing it or")
print("   putting it in JSON raises -- correctly.")
print()
print("4. bytes METHODS THAT LOOK LIKE str METHODS ARE ASCII-ONLY")
b = "CAFÉ".encode("utf-8")
print(f"   {b!r}.lower() -> {b.lower()!r}")
print(f"   'CAFÉ'.lower() -> {'CAFÉ'.lower()!r}")
print("   The bytes version lowercased C, A, F and left the two bytes of É")
print("   alone -- because bytes.lower() is defined on ASCII and nothing else.")
print("   That is documented and it is on purpose: bytes have no encoding, so")
print("   there is no other case mapping it could apply. It is still a silent")
print("   wrong answer if you thought you were working with text.")
print()
print("THE ONE-LINE VERSION")
print("   Say the encoding out loud at every boundary, treat filenames as a")
print("   special case that Python has already solved for you, and never let a")
print("   bytes object anywhere near a method whose name suggests it knows")
print("   about language.")

assert os.fsencode(os.fsdecode(b"caf\xe9.txt")) == b"caf\xe9.txt"
assert "CAFÉ".encode().lower() != "café".encode()
