"""Answer key: five scars, each one still reachable from a keyboard."""
print("1. THE CASE BIT -- ASCII 1963")
for a, b in [("A", "a"), ("Z", "z")]:
    print(f"   {a} {ord(a):#04x} {ord(a):07b}    {b} {ord(b):#04x} {ord(b):07b}   differ in bit 5")
print(f"   chr(ord('A') ^ 0x20) = {chr(ord('A') ^ 0x20)!r}")
print("   The committee laid the two alphabets 0x20 apart so a teleprinter")
print("   could shift case by flipping one wire. The scar: every program that")
print("   still does case with XOR breaks on the first non-ASCII letter, and")
print("   'ß'.upper() is two characters, which no bit flip can produce.")
print()
print("2. \\r\\n -- THE CARRIAGE AND THE PLATEN, 1901")
print("   CR returned the carriage; LF advanced the paper. Two motions, two")
print("   characters, because the machine really did do two things -- and a")
print("   Teletype needed the time both took.")
print(f"   'a\\r\\nb'.split(chr(10)) -> {'a\r\nb'.split(chr(10))}")
print("   The scar: half the world kept both bytes and half kept one, so every")
print("   text file crossing between them has an invisible byte at the end of")
print("   every line, and every tool that shows you TEXT hides it.")
print()
print("3. latin-1 AS A BYTE HACK")
b = bytes(range(256))
print(f"   bytes(range(256)).decode('latin-1') -> {len(b.decode('latin-1'))} characters, no error")
print("   Latin-1 maps all 256 byte values to code points 0-255, so it is TOTAL")
print("   -- it can never fail. That makes it the standard trick for smuggling")
print("   arbitrary bytes through a text API, and the standard cause of")
print("   mojibake, and the reason a wrong decode is silent rather than loud.")
print()
print("4. .length COUNTING THE WRONG THING")
s = "😀"
print(f"   {s}   Python len {len(s)}   utf-16 units {len(s.encode('utf-16-le')) // 2}"
      f"   utf-8 bytes {len(s.encode())}   graphemes 1")
print("   Four numbers, four correct answers, one question. The systems that")
print("   answer 2 adopted Unicode while it was still 16 bits wide.")
print()
print("5. THE EXTRACT THAT IS NOT ASCII AT ALL")
print("   EBCDIC is not a rearrangement of ASCII: its letters come in three")
print("   runs with gaps, so 'is this a letter' cannot be a range check and")
print("   sorting bytes does not sort the alphabet.")
for enc, label in [("cp037", "EBCDIC cp037"), ("ascii", "ASCII")]:
    print(f"   {label:<14} A={('A'.encode(enc)[0]):#04x} I={('I'.encode(enc)[0]):#04x} "
          f"J={('J'.encode(enc)[0]):#04x} S={('S'.encode(enc)[0]):#04x}")
print("   Look at I to J in the EBCDIC row: the run breaks. That is the scar a")
print("   mainframe extract still carries into a modern pipeline.")
print()
print("THE POINT OF THE HISTORY")
print("   Not one of those five was a mistake at the time. Each was the right")
print("   answer to a real constraint -- a wire, a platen, a byte budget, a")
print("   16-bit machine word, a punched card. The mess is what you get when")
print("   six good local decisions have to keep working together for sixty")
print("   years, which is also a fair description of any system you maintain.")

assert bytes(range(256)).decode("latin-1").encode("latin-1") == bytes(range(256))
assert "I".encode("cp037")[0] + 1 != "J".encode("cp037")[0]
