"""Answer key: what those four systems adopted, and why they cannot leave."""
S = "😀"

print("WHAT UNICODE WAS WHEN THEY ADOPTED IT")
print("   Until Unicode 2.0 (1996) the whole character set fit in 16 bits:")
print("   65,536 code points, one 16-bit unit each, fixed width. A char was a")
print("   number, an array of them was a string, and s[i] was O(1) and correct.")
print("   Java (1995), Windows NT (1993), JavaScript (1995) and SAP all took")
print("   that deal, and it was a GOOD deal.")
print()
print("THEN THE SET GREW, AND FIXED WIDTH BECAME A SURROGATE PAIR")
print(f"   {S}  U+{ord(S):04X}")
print(f"   utf-16 units  {len(S.encode('utf-16-le')) // 2}   bytes {len(S.encode('utf-16-le'))}")
print(f"   utf-8 bytes   {len(S.encode('utf-8'))}")
print(f"   code points   {len(S)}")
print("   Every one of those four systems now reports this character's length")
print("   as 2, because their unit is the 16-bit code unit and always was.")
print()
print("WHY NONE OF THEM CAN CHANGE IT")
print("   The type is in every public API. Java's String.charAt, JavaScript's")
print("   string indexing, the Windows W-suffixed API, ABAP's character")
print("   fields -- changing the unit would change the meaning of every")
print("   existing index in every program ever compiled against them. So the")
print("   cost is not technical difficulty; it is that the width is part of a")
print("   contract with thirty years of callers.")
print()
print("ABAP'S SECOND REASON, WHICH THE OTHER THREE DO NOT HAVE")
print("   ABAP field offsets are ARITHMETIC: name+10(20) means 'twenty units")
print("   starting at unit ten', and that appears in production code written")
print("   against fixed-width structures. With a fixed-width encoding the")
print("   arithmetic is a fact about the layout. With a variable-width one it")
print("   would be a guess -- so UCS-2/UTF-16 is not merely SAP's historical")
print("   choice, it is what makes an enormous body of existing code mean")
print("   anything at all.")
print()
print("WHAT THIS COSTS YOU IN PRACTICE")
print("   A VARCHAR(1) that rejects an emoji is counting code units.")
print("   A JavaScript .length of 2 for one character is counting code units.")
print("   A JSON escape of an emoji is TWO \\u escapes, because \\u names a code")
print("   unit -- and that is how a surrogate pair reaches a format whose")
print("   transport encoding, by RFC 8259, is UTF-8.")
print(f"   json.dumps: {S!r} -> " + '"\\ud83d\\ude00"')
print()
print("THE LESSON THAT TRANSFERS")
print("   Nobody chose UTF-16 over UTF-8. They chose a fixed-width 16-bit")
print("   character set, correctly, before it stopped being one -- and then")
print("   inherited a variable-width encoding they never signed up for. When")
print("   you pick a text representation today you are making the same kind of")
print("   bet, and the question to ask is what happens when the assumption")
print("   underneath it stops holding.")

assert len("😀".encode("utf-16-le")) == 4
assert len("😀") == 1
